---
openapi: 3.0.3

info:
  title: AEM Forms as a Cloud Service - Document Utilities HTTP APIs
  description: |
    # Introduction
    Document Utilities APIs provide ability to generate, convert,
    transform and extract information from PDF and XDP file formats.
  version: 0.0.1-experimental

externalDocs:
  description: |
    Overview of AEM Forms as a Cloud Service - Document Utilities
  url: https://developer.adobe.com/experience-manager-forms-cloud-service-developer-reference/references/pdf-utility-sync/

servers:
  # TODO: add test server URL
  - url: https://TEST-SERVER-URL/adobe/forms/document

security:
  - BearerAuth: []

tags:
  - name: Document Extraction
    description: |
      Extract information or data from a PDF
  - name: Document Conversion
    description: |
      Convert various source formats to/from PDF

x-tagGroups:
  - name: AEM Forms - Communications API
    tags:
      - Document Extraction
      - Document Conversion
  - name: Models
    tags:
      - PDFPropertiesRequest
      - PDFPropertiesResponse
paths:
  /extract/pdfproperties:
    $ref: "./extract/pdfproperties.yaml#/paths/~1pdfproperties"

  /convert/pdftoxdp:
    $ref: "./convert/pdftoxdp.yaml#/paths/~1pdftoxdp"

components:
  securitySchemes:
    BearerAuth:
      $ref: "./_common/security.yaml#/components/securitySchemes/BearerAuth"